export type Sura = {
	slug: string;
	id: string;
	name: string;
	nameAl: string;
	shqiperuar?: string;
	arabicName: string;
	place: string;
	ayahs: number;
	words: number;
	chars: number;
	theme?: string;
	keyMessage?: string;
	order: number;
	revealOrder: number;
	juz?: number;
};

export const surahs: Sura[] = [
	{
		id: '001',
		slug: 'al-fatiha',
		name: 'Al-Fātiha',
		shqiperuar: 'Al-Fatihah',
		nameAl: 'Hapja',
		arabicName: 'الفاتحة',
		place: 'Mekë',
		ayahs: 7,
		words: 74,
		chars: 314,
		theme: 'Lavdërimi i Allahut, adhurimi vetëm i Tij dhe kërkimi i udhëzimit në rrugën e drejtë.',
		keyMessage: 'Të kërkojmë nga Allahu udhëzim dhe ndihmë në çdo hap të jetës.',
		order: 1,
		revealOrder: 5,
	},
	{
		id: '002',
		slug: 'al-baqara',
		name: 'Al-Baqara',
		shqiperuar: 'Al-Bekare',
		nameAl: 'Lopa',
		arabicName: 'البقرة',
		place: 'Medinë',
		ayahs: 286,
		words: 12316,
		chars: 52639,
		theme: 'Besimi, adhurimi, ligjet e jetës, familja, drejtësia, marrëdhëniet shoqërore dhe sprovat e Beni Israilëve.',
		keyMessage: 'Besimi duhet të shndërrohet në mënyrë jetese dhe bindje praktike ndaj Allahut.',
		order: 2,
		revealOrder: 87,
	},
	{
		id: '003',
		slug: 'aal-imran',
		name: 'Āl-`Imrān',
		shqiperuar: 'Ali Imran',
		nameAl: 'Imrani (babai i Musës a.s.)',
		arabicName: 'آل عمران',
		place: 'Medinë',
		ayahs: 200,
		words: 7080,
		chars: 30276,
		theme: 'Teuhidi, Merjemja dhe Isai, ithtarët e Librit, sprovat dhe mësimet nga Uhudi.',
		keyMessage: 'Qëndrueshmëria në besim dhe kthimi tek Allahu pas gabimit janë burim force.',
		order: 3,
		revealOrder: 89,
	},
	{
		id: '004',
		slug: 'an-nisa',
		name: "An-Nisā'",
		nameAl: 'Gruaja',
		shqiperuar: 'En-Nisa',
		arabicName: 'النّساء',
		place: 'Medinë',
		ayahs: 176,
		words: 7347,
		chars: 31845,
		theme: 'Drejtësia, të drejtat e grave dhe jetimëve, martesa, trashëgimia, pasuria dhe drejtësia shoqërore.',
		keyMessage: 'Besimi kërkon drejtësi dhe mbrojtje të të drejtave të të dobëtëve.',
		order: 4,
		revealOrder: 92,
	},
	{
		id: '005',
		slug: 'al-maida',
		name: "Al-Mā'ida",
		shqiperuar: 'El-Maide',
		nameAl: 'Tryeza',
		arabicName: 'المآئدة',
		place: 'Medinë',
		ayahs: 120,
		words: 5598,
		chars: 23932,
		theme: 'Marrëveshjet, hallalli dhe harami, drejtësia, abdesi dhe marrëdhëniet me ithtarët e Librit.',
		keyMessage: 'Besimtari duhet të jetë besnik ndaj marrëveshjeve dhe kufijve të Allahut.',
		order: 5,
		revealOrder: 112,
	},
	{
		id: '006',
		slug: 'al-anam',
		name: 'Al-An`ām',
		shqiperuar: 'El-Enam',
		nameAl: 'Bagëtia',
		arabicName: 'الانعام',
		place: 'Mekë',
		ayahs: 165,
		words: 6226,
		chars: 26109,
		theme: 'Teuhidi, argumentet e krijimit dhe refuzimi i idhujtarisë.',
		keyMessage: 'Reflektimi mbi krijimin e çon njeriun drejt njohjes së Krijuesit.',
		order: 6,
		revealOrder: 55,
	},
	{
		id: '007',
		slug: 'al-araf',
		name: 'Al-A`rāf',
		shqiperuar: 'El-Araf',
		nameAl: 'Lartësitë',
		arabicName: 'الأعراف',
		place: 'Mekë',
		ayahs: 206,
		words: 6796,
		chars: 28550,
		theme: 'Ademi dhe Iblisi dhe historitë e shumë popujve e pejgamberëve, me theks te bindja dhe pasojat e mohimit.',
		keyMessage: 'Arroganca e largon njeriun nga e vërteta; bindja dhe pendimi e shpëtojnë.',
		order: 7,
		revealOrder: 39,
	},
	{
		id: '008',
		slug: 'al-anfal',
		name: "Al-'Anfāl",
		shqiperuar: 'El-Enfal',
		nameAl: 'Plaëkat e luftës',
		arabicName: 'الأنفال',
		place: 'Medinë',
		ayahs: 75,
		words: 2525,
		chars: 10834,
		theme: 'Beteja e Bedrit, bindja, uniteti, disiplina dhe rregullat në konflikt.',
		keyMessage: 'Fitorja lidhet me besimin, unitetin dhe disiplinën, jo vetëm me fuqinë materiale.',
		order: 8,
		revealOrder: 88,
	},
	{
		id: '009',
		slug: 'at-tawba',
		name: 'At-Tawba',
		shqiperuar: 'Et-Teube',
		nameAl: 'Pendimi',
		arabicName: 'التوبة',
		place: 'Medinë',
		ayahs: 129,
		words: 5169,
		chars: 22679,
		theme: 'Pendimi, sinqeriteti, hipokrizia, marrëveshjet dhe ngjarjet e Tebukut.',
		keyMessage: 'Pendimi i sinqertë e rikthen njeriun tek Allahu.',
		order: 9,
		revealOrder: 113,
	},
	{
		id: '010',
		slug: 'yunus',
		name: 'Yūnus',
		nameAl: 'Junusi (I dërguar)',
		shqiperuar: 'Junus',
		arabicName: 'يونس',
		place: 'Mekë',
		ayahs: 109,
		words: 3588,
		chars: 14947,
		theme: 'Besimi përballë mohimit, argumentet e shpalljes dhe shembujt e Musait, Faraonit dhe Junusit.',
		keyMessage: 'Të ruajmë besimin dhe durimin edhe kur e vërteta refuzohet.',
		order: 10,
		revealOrder: 51,
	},
	{
		id: '011',
		slug: 'hud',
		name: 'Hūd',
		nameAl: 'Hudi (I dërguar)',
		shqiperuar: 'Hud',
		arabicName: 'هود',
		place: 'Mekë',
		ayahs: 123,
		words: 3930,
		chars: 16168,
		theme: 'Qëndrueshmëria në të vërtetën dhe historitë e Nuhut, Hudit, Salihut, Ibrahimit, Lutit, Shuajbit dhe Musait.',
		keyMessage: 'Qëndro i drejtë dhe mos u lëkund përballë vështirësive.',
		order: 11,
		revealOrder: 52,
	},
	{
		id: '012',
		slug: 'yusuf',
		name: 'Yūsuf',
		nameAl: 'Jusuf (I dërguar)',
		shqiperuar: 'Jusuf',
		arabicName: 'يوسف',
		place: 'Mekë',
		ayahs: 111,
		words: 3566,
		chars: 14512,
		theme: 'Historia e Jusufit: sprova, ndarja, padrejtësia, durimi, falja dhe përfundimi i mirë.',
		keyMessage: 'Durimi dhe besimi në planin e Allahut mund ta shndërrojnë sprovën në mirësi.',
		order: 12,
		revealOrder: 53,
	},
	{
		id: '013',
		slug: 'ar-rad',
		name: 'Ar-Ra`d',
		shqiperuar: 'Er-Rad',
		nameAl: 'Bubullima',
		arabicName: 'الرّعد',
		place: 'Medinë',
		ayahs: 43,
		words: 1701,
		chars: 7360,
		theme: 'Shenjat e fuqisë së Allahut në natyrë, shpallja, e vërteta dhe e pavërteta.',
		keyMessage: 'Zemrat gjejnë qetësi përmes përmendjes së Allahut.',
		order: 13,
		revealOrder: 96,
	},
	{
		id: '014',
		slug: 'ibrahim',
		name: 'Ibrāhīm',
		shqiperuar: 'Ibrahim',
		nameAl: 'Ibrahimi (I dërguar)',
		arabicName: 'إبراهيم',
		place: 'Medinë',
		ayahs: 52,
		words: 1649,
		chars: 7050,
		theme: 'Teuhidi, mirënjohja, profetët dhe lutjet e Ibrahimit për familjen dhe pasardhësit.',
		keyMessage: 'Mirënjohja e forcon besimin dhe mosmirënjohja e çon njeriun në humbje.',
		order: 14,
		revealOrder: 72,
	},
	{
		id: '015',
		slug: 'al-hijr',
		name: 'Al-Hijr',
		shqiperuar: 'El-Hixhr',
		nameAl: 'Hixhr',
		arabicName: 'الحجر',
		place: 'Mekë',
		ayahs: 99,
		words: 1389,
		chars: 5896,
		theme: 'Ruajtja e shpalljes, krijimi, Ademi dhe Iblisi dhe shembujt e popujve të mëparshëm.',
		keyMessage: "E vërteta e shpallur nga Allahu është e mbrojtur dhe njeriu duhet t'i bindet asaj.",
		order: 15,
		revealOrder: 54,
	},
	{
		id: '016',
		slug: 'an-nahl',
		name: 'An-Nahl',
		shqiperuar: 'En-Nahl',
		nameAl: 'Bleta',
		arabicName: 'النّحل',
		place: 'Mekë',
		ayahs: 128,
		words: 3757,
		chars: 15908,
		theme: 'Begatitë e Allahut, krijimi, mirënjohja, drejtësia dhe thirrja në urtësi.',
		keyMessage: 'Të njohim begatitë e Allahut dhe të jemi mirënjohës.',
		order: 16,
		revealOrder: 70,
	},
	{
		id: '017',
		slug: 'al-isra',
		name: "Al-Isrā'",
		shqiperuar: 'El-Isra',
		nameAl: 'Israja dhe Miraxhi',
		arabicName: 'الإسرا',
		place: 'Mekë',
		ayahs: 111,
		words: 3223,
		chars: 13549,
		theme: 'Israja, përgjegjësia morale, nderimi i prindërve, drejtësia dhe udhëzimi i Kuranit.',
		keyMessage: 'Njeriu duhet të ndërtojë jetën mbi adhurimin, moralin dhe drejtësinë.',
		order: 17,
		revealOrder: 50,
	},
	{
		id: '018',
		slug: 'al-kahf',
		name: 'Al-Kahf',
		shqiperuar: 'El-Kehf',
		nameAl: 'Shpella',
		arabicName: 'الكهف',
		place: 'Mekë',
		ayahs: 110,
		words: 3350,
		chars: 13823,
		theme: 'Banorët e shpellës, dy pronarët e kopshteve, Musai dhe Hidri, Dhul-Karnejni; sprovat e fesë, pasurisë, dijes dhe pushtetit.',
		keyMessage: 'Besimi, modestia dhe mbështetja tek Allahu janë mbrojtje nga sprovat.',
		order: 18,
		revealOrder: 69,
	},
	{
		id: '019',
		slug: 'maryam',
		name: 'Maryam',
		shqiperuar: 'Merjem',
		nameAl: 'Merjeme (nëna e Isës a.s.)',
		arabicName: 'مريم',
		place: 'Mekë',
		ayahs: 98,
		words: 2036,
		chars: 8188,
		theme: 'Merjemja dhe lindja e Isait, Zekerijaja, Jahjaja, Ibrahimi dhe profetët e tjerë.',
		keyMessage: 'Mëshira dhe fuqia e Allahut shfaqen edhe në rrethana që duken të pamundura.',
		order: 19,
		revealOrder: 44,
	},
	{
		id: '020',
		slug: 'ta-ha',
		name: 'Tā-Hā',
		shqiperuar: 'Ta Ha',
		nameAl: 'Ta-Ha',
		arabicName: 'طه',
		place: 'Mekë',
		ayahs: 135,
		words: 2830,
		chars: 11608,
		theme: 'Musai dhe Faraoni, shpallja, Ademi dhe përgjegjësia e njeriut.',
		keyMessage: 'Mos u frikëso nga e vërteta; Allahu e mbështet të dërguarin dhe besimtarin.',
		order: 20,
		revealOrder: 45,
	},
	{
		id: '021',
		slug: 'al-anbiya',
		name: 'Al-Anbiyā',
		nameAl: 'Pejgamberat',
		shqiperuar: 'El-Enbija',
		arabicName: 'الأنبياء',
		place: 'Mekë',
		ayahs: 112,
		words: 1903,
		chars: 7743,
		theme: 'Profetët, teuhidi, ringjallja dhe sprovat e të dërguarve.',
		keyMessage: 'Të gjithë profetët thirrën në adhurimin e një Zoti.',
		order: 21,
		revealOrder: 73,
	},
	{
		id: '022',
		slug: 'al-hajj',
		name: 'Al-Ḥajj',
		nameAl: 'Haxh',
		shqiperuar: 'El-Haxhxh',
		arabicName: 'الحج',
		place: 'Medinë',
		ayahs: 78,
		words: 1279,
		chars: 5104,
		theme: 'Ringjallja, Haxhi, adhurimi, sakrifica dhe përgjegjësia e komunitetit besimtar.',
		keyMessage: 'Adhurimi duhet të shoqërohet me devotshmëri dhe përgjegjësi.',
		order: 22,
		revealOrder: 103,
	},
	{
		id: '023',
		slug: 'al-muminun',
		name: 'Al-Mu’minūn',
		shqiperuar: 'El-Muminun',
		nameAl: 'Besimtarët',
		arabicName: 'المؤمنون',
		place: 'Mekë',
		ayahs: 118,
		words: 1840,
		chars: 7376,
		theme: 'Cilësitë e besimtarëve të suksesshëm, krijimi i njeriut dhe historitë e profetëve.',
		keyMessage: 'Suksesi i vërtetë lidhet me besimin, namazin, pastërtinë morale dhe amanetin.',
		order: 23,
		revealOrder: 74,
	},
	{
		id: '024',
		slug: 'an-nur',
		name: 'An-Nūr',
		shqiperuar: 'En-Nur',
		nameAl: 'Drita',
		arabicName: 'النور',
		place: 'Medinë',
		ayahs: 64,
		words: 1317,
		chars: 5596,
		theme: 'Pastërtia morale, familja, shpifja, modestia, privatësia dhe rregullat shoqërore.',
		keyMessage: 'Drita e Allahut kërkon pastërti të zemrës, sjelljes dhe shoqërisë.',
		order: 24,
		revealOrder: 102,
	},
	{
		id: '025',
		slug: 'al-furqan',
		name: 'Al-Furqān',
		shqiperuar: 'El-Furkan',
		nameAl: 'Standardi',
		arabicName: 'الفرقان',
		place: 'Mekë',
		ayahs: 77,
		words: 898,
		chars: 3902,
		theme: 'Kriteri mes së vërtetës dhe së pavërtetës dhe cilësitë e robërve të Mëshiruesit.',
		keyMessage: 'Besimtari dallon të vërtetën dhe e jeton atë me përulësi.',
		order: 25,
		revealOrder: 42,
	},
	{
		id: '026',
		slug: 'ash-shuara',
		name: 'Ash-Shu‘arā’',
		shqiperuar: 'Esh-Shuara',
		nameAl: 'Poetët',
		arabicName: 'الشعراء',
		place: 'Mekë',
		ayahs: 227,
		words: 1324,
		chars: 5582,
		theme: 'Historitë e Musait, Ibrahimit, Nuhut, Hudit, Salihut, Lutit dhe Shuajbit.',
		keyMessage: 'Mesazhi i profetëve përsëritet: adhuroni Allahun dhe binduni të vërtetës.',
		order: 26,
		revealOrder: 47,
	},
	{
		id: '027',
		slug: 'an-naml',
		name: 'An-Naml',
		shqiperuar: 'En-Neml',
		nameAl: 'Milingonat',
		arabicName: 'النمل',
		place: 'Mekë',
		ayahs: 93,
		words: 1236,
		chars: 4960,
		theme: 'Sulejmani dhe mbretëresha e Sebeut, Musai, Salihu dhe historitë e shenjave të Allahut.',
		keyMessage: 'Dija dhe pushteti duhet të shoqërohen me mirënjohje ndaj Allahut.',
		order: 27,
		revealOrder: 48,
	},
	{
		id: '028',
		slug: 'al-qasas',
		name: 'Al-Qaṣaṣ',
		nameAl: 'Tregimet',
		shqiperuar: 'El-Kasas',
		arabicName: 'القصص',
		place: 'Mekë',
		ayahs: 88,
		words: 1433,
		chars: 5804,
		theme: 'Jeta e Musait, Faraoni dhe historia e Karunit.',
		keyMessage: 'Allahu e mbron të dobëtin dhe drejtësia përfundimisht triumfon.',
		order: 28,
		revealOrder: 49,
	},
	{
		id: '029',
		slug: 'al-ankabut',
		name: 'Al-‘Ankabūt',
		shqiperuar: 'El-Ankebut',
		nameAl: 'Merimanga',
		arabicName: 'العنكبوت',
		place: 'Mekë',
		ayahs: 69,
		words: 982,
		chars: 4192,
		theme: 'Sprovat e besimit, shembujt e profetëve dhe dobësia e mbështetjeve të rreme.',
		keyMessage: 'Besimi sprovohet; mbështetjet e tjera janë të brishta si rrjeta e merimangës.',
		order: 29,
		revealOrder: 85,
	},
	{
		id: '030',
		slug: 'ar-rum',
		name: 'Ar-Rūm',
		shqiperuar: 'Er-Rum',
		nameAl: 'Romakët',
		arabicName: 'الروم',
		place: 'Mekë',
		ayahs: 60,
		words: 818,
		chars: 3460,
		theme: 'Humbja dhe fitorja e romakëve, shenjat e Allahut, martesa dhe krijimi.',
		keyMessage: 'Historia dhe natyra janë shenja që ftojnë në reflektim dhe besim.',
		order: 30,
		revealOrder: 84,
	},
	{
		id: '031',
		slug: 'luqman',
		name: 'Luqmān',
		shqiperuar: 'Lukman',
		nameAl: 'Lukmani',
		arabicName: 'لقمان',
		place: 'Mekë',
		ayahs: 34,
		words: 550,
		chars: 2195,
		theme: 'Urtësia e Lukmanit, teuhidi, mirënjohja, namazi, modestia dhe edukimi i fëmijëve.',
		keyMessage: 'Urtësia fillon me teuhidin, mirënjohjen dhe sjelljen e mirë.',
		order: 31,
		revealOrder: 57,
	},
	{
		id: '032',
		slug: 'as-sajda',
		name: 'As-Sajdah',
		nameAl: 'Sexhdeja',
		shqiperuar: 'Es-Sexhde',
		arabicName: 'السجدة',
		place: 'Mekë',
		ayahs: 30,
		words: 375,
		chars: 1523,
		theme: 'Krijimi, shpallja, ringjallja dhe përulja e besimtarëve.',
		keyMessage: 'Njeriu e njeh madhështinë e Allahut duke reflektuar mbi krijimin dhe ringjalljen.',
		order: 32,
		revealOrder: 75,
	},
	{
		id: '033',
		slug: 'al-ahzab',
		name: 'Al-Aḥzāb',
		shqiperuar: 'El-Ahzab',
		nameAl: 'Aleancat',
		arabicName: 'الأحزاب',
		place: 'Medinë',
		ayahs: 73,
		words: 1303,
		chars: 5385,
		theme: 'Beteja e Hendekut, familja e Profetit, rregullat shoqërore dhe morali.',
		keyMessage: 'Besnikëria, durimi dhe respekti për udhëzimin profetik ndërtojnë një shoqëri të shëndoshë.',
		order: 33,
		revealOrder: 90,
	},
	{
		id: '034',
		slug: 'saba',
		name: 'Saba’',
		nameAl: "Sebe'ë",
		shqiperuar: 'Sebe',
		arabicName: 'سبإ',
		place: 'Mekë',
		ayahs: 54,
		words: 884,
		chars: 3618,
		theme: 'Populli i Sebeut, Davudi, Sulejmani, mirënjohja dhe pasojat e mohimit.',
		keyMessage: "Begatitë kërkojnë mirënjohje; mosmirënjohja mund t'i humbë ato.",
		order: 34,
		revealOrder: 58,
	},
	{
		id: '035',
		slug: 'al-fatir',
		name: 'Al-Fāṭir',
		shqiperuar: 'El-Fatir',
		nameAl: 'Krijuesi',
		arabicName: 'فاطر',
		place: 'Mekë',
		ayahs: 45,
		words: 780,
		chars: 3223,
		theme: 'Fuqia e Krijuesit, krijimi, engjëjt, mirësitë dhe dallimi mes dijes dhe injorancës.',
		keyMessage: 'Njohja e Allahut duhet të sjellë frikë-respekt dhe mirënjohje.',
		order: 35,
		revealOrder: 43,
	},
	{
		id: '036',
		slug: 'ya-sin',
		name: 'Yā-Sīn',
		nameAl: 'Jasin',
		shqiperuar: 'Jasin',
		arabicName: 'يس',
		place: 'Mekë',
		ayahs: 83,
		words: 807,
		chars: 3028,
		theme: 'Shpallja, ringjallja, shenjat e Allahut dhe përgjegjësia e njeriut.',
		keyMessage: 'Kujtimi i ringjalljes e zgjon ndërgjegjen dhe e orienton jetën drejt Allahut.',
		order: 36,
		revealOrder: 41,
	},
	{
		id: '037',
		slug: 'as-saffat',
		name: 'Aṣ-Ṣāffāt',
		shqiperuar: 'Es-Safat',
		nameAl: 'Të rreshtuarit',
		arabicName: 'الصافات',
		place: 'Mekë',
		ayahs: 182,
		words: 865,
		chars: 3505,
		theme: 'Engjëjt, profetët, Ibrahimi dhe sprova e sakrificës së tij.',
		keyMessage: 'Sinqeriteti dhe bindja ndaj Allahut janë themeli i shpëtimit.',
		order: 37,
		revealOrder: 56,
	},
	{
		id: '038',
		slug: 'sad',
		name: 'Ṣād',
		nameAl: 'Sad',
		shqiperuar: 'Sad',
		arabicName: 'ص',
		place: 'Mekë',
		ayahs: 88,
		words: 733,
		chars: 2964,
		theme: 'Davudi, Sulejmani, Ejubi, krijimi i Ademit dhe sprova e Iblisit.',
		keyMessage: 'Pushteti dhe sprovat kërkojnë drejtësi, durim dhe pendim.',
		order: 38,
		revealOrder: 38,
	},
	{
		id: '039',
		slug: 'az-zumar',
		name: 'Az-Zumar',
		nameAl: 'Turmat',
		shqiperuar: 'Ez-Zumer',
		arabicName: 'الزمر',
		place: 'Mekë',
		ayahs: 75,
		words: 1186,
		chars: 4827,
		theme: 'Sinqeriteti në adhurim, pendimi, ringjallja dhe grupet e njerëzve në Ditën e Gjykimit.',
		keyMessage: 'Mos e humb shpresën nga mëshira e Allahut dhe adhuroje Atë me sinqeritet.',
		order: 39,
		revealOrder: 59,
	},
	{
		id: '040',
		slug: 'al-ghafir',
		name: 'Al-Ghāfir',
		shqiperuar: 'El-Gafir',
		nameAl: 'Falësi',
		arabicName: 'غافر',
		place: 'Mekë',
		ayahs: 85,
		words: 1228,
		chars: 4968,
		theme: 'Falja e Allahut, Musai dhe Faraoni, besimtari nga familja e Faraonit.',
		keyMessage: 'Allahut i drejtohet njeriu me pendim dhe lutje; mëshira e Tij është e gjerë.',
		order: 40,
		revealOrder: 60,
	},
	{
		id: '041',
		slug: 'fussilat',
		name: 'Fussilat',
		nameAl: 'Të shpjeguara qartë',
		shqiperuar: 'Fusilet',
		arabicName: 'فصّلت',
		place: 'Mekë',
		ayahs: 54,
		words: 1648,
		chars: 6929,
		theme: 'Krijimi, shpallja, shenjat e Allahut dhe qëndrueshmëria në besim.',
		keyMessage: 'Të qëndrosh drejt dhe të mos lëkundesh është pjesë e besimit të vërtetë.',
		order: 41,
		revealOrder: 61,
	},
	{
		id: '042',
		slug: 'ash-shura',
		name: 'Ash-Shūrā',
		shqiperuar: 'Esh-Shura',
		nameAl: 'Këshillimi',
		arabicName: 'الشّورى',
		place: 'Mekë',
		ayahs: 53,
		words: 1682,
		chars: 7227,
		theme: 'Shpallja, uniteti i mesazhit profetik, falja dhe konsultimi.',
		keyMessage: 'Çështjet shoqërore duhet të trajtohen me drejtësi, falje dhe konsultim.',
		order: 42,
		revealOrder: 62,
	},
	{
		id: '043',
		slug: 'az-zukhruf',
		name: 'Az-Zukhruf',
		nameAl: 'Stolitë',
		shqiperuar: 'Ez-Zuhruf',
		arabicName: 'الزّخرف',
		place: 'Mekë',
		ayahs: 89,
		words: 1785,
		chars: 7486,
		theme: 'Vlera e kësaj bote, idhujtaria, Musai, Isai dhe pasojat e mohimit.',
		keyMessage: 'Pasuria dhe zbukurimet e kësaj bote nuk janë masë e vlerës tek Allahu.',
		order: 43,
		revealOrder: 63,
	},
	{
		id: '044',
		slug: 'ad-dukhan',
		name: 'Ad-Dukhān',
		shqiperuar: 'Ed-Duhan',
		nameAl: 'Tymi',
		arabicName: 'الدّخان',
		place: 'Mekë',
		ayahs: 59,
		words: 710,
		chars: 3023,
		theme: 'Shpallja, paralajmërimi, Faraoni dhe pasojat e mohimit.',
		keyMessage: 'Mëshira dhe paralajmërimi i Allahut kërkojnë që njeriu të zgjohet para se të jetë vonë.',
		order: 44,
		revealOrder: 64,
	},
	{
		id: '045',
		slug: 'al-jathiya',
		name: 'Al-Jāthiya',
		shqiperuar: 'El-Xhathije',
		nameAl: 'Të gjunjëzuarit',
		arabicName: 'الجاثية',
		place: 'Mekë',
		ayahs: 37,
		words: 999,
		chars: 4167,
		theme: 'Shenjat e Allahut, ligji moral dhe dita kur popujt do të gjunjëzohen para gjykimit.',
		keyMessage: 'Mos ndiq dëshirat kundër udhëzimit të Allahut.',
		order: 45,
		revealOrder: 65,
	},
	{
		id: '046',
		slug: 'al-ahqaf',
		name: 'Al-Ahqāf',
		nameAl: 'Al-Ahqaf',
		shqiperuar: 'El-Ahkaf',
		arabicName: 'الأحقاف',
		place: 'Mekë',
		ayahs: 35,
		words: 1311,
		chars: 5561,
		theme: 'Populli i Adit, bindja ndaj prindërve, Xhinët që dëgjojnë Kuranin dhe paralajmërimi.',
		keyMessage: 'Durimi dhe mirënjohja janë rrugë e besimtarit.',
		order: 46,
		revealOrder: 66,
	},
	{
		id: '047',
		slug: 'muhammad',
		name: 'Muhammad',
		nameAl: 'Muhammad ﷺ',
		shqiperuar: 'Muhammad ﷺ',
		arabicName: 'محمّد',
		place: 'Medinë',
		ayahs: 38,
		words: 1099,
		chars: 4853,
		theme: 'Besimi, lufta, bindja, hipokrizia dhe qëndrueshmëria e komunitetit.',
		keyMessage: 'Besimi kërkon vepra, sakrificë dhe bindje të sinqertë.',
		order: 47,
		revealOrder: 95,
	},
	{
		id: '048',
		slug: 'al-fath',
		name: 'Al-Fath',
		nameAl: 'Fitorja',
		shqiperuar: 'El-Fet`h',
		arabicName: 'الفتح',
		place: 'Medinë',
		ayahs: 29,
		words: 1169,
		chars: 5157,
		theme: 'Marrëveshja e Hudejbijes dhe fitorja që erdhi përmes saj.',
		keyMessage: 'Jo çdo fitore duket menjëherë si fitore; besimi te urtësia e Allahut është thelbësor.',
		order: 48,
		revealOrder: 111,
	},
	{
		id: '049',
		slug: 'al-hujurat',
		name: 'Al-Hujurāt',
		nameAl: 'Dhomat',
		shqiperuar: 'El-Huxhurat',
		arabicName: 'الحجرات',
		place: 'Medinë',
		ayahs: 18,
		words: 663,
		chars: 2889,
		theme: 'Etika ndaj Profetit, verifikimi i lajmeve, pajtimi, ndalimi i talljes, shpifjes dhe paragjykimit.',
		keyMessage: 'Nderi i njeriut, respekti dhe vëllazëria janë pjesë e besimit.',
		order: 49,
		revealOrder: 106,
	},
	{
		id: '050',
		slug: 'qaf',
		name: 'Qāf',
		nameAl: 'Kaf',
		shqiperuar: 'Kaf',
		arabicName: 'ق',
		place: 'Mekë',
		ayahs: 45,
		words: 762,
		chars: 3150,
		theme: 'Ringjallja, vdekja, regjistrimi i veprave dhe fuqia e Allahut.',
		keyMessage: 'Çdo fjalë dhe vepër ka përgjegjësi; ringjallja është e sigurt.',
		order: 50,
		revealOrder: 34,
	},
	{
		id: '051',
		slug: 'adh-dhariyat',
		name: 'Adh-Dhāriyāt',
		nameAl: 'Erërat ',
		shqiperuar: 'Edh-Dharijat',
		arabicName: 'الذّاريات',
		place: 'Mekë',
		ayahs: 60,
		words: 753,
		chars: 3182,
		theme: 'Fuqia e Allahut, furnizimi, profetët dhe qëllimi i krijimit.',
		keyMessage: 'Qëllimi i krijimit është adhurimi i Allahut.',
		order: 51,
		revealOrder: 67,
	},
	{
		id: '052',
		slug: 'at-tur',
		name: 'At-Tūr',
		nameAl: 'Mali Tur',

		shqiperuar: 'Et-Tur',
		arabicName: 'الطّور',
		place: 'Medinë',
		ayahs: 49,
		words: 680,
		chars: 2852,
		theme: 'Dita e Gjykimit, Xheneti dhe argumentet ndaj mohuesve.',
		keyMessage: 'Premtimi i Allahut për besimtarët është i vërtetë.',
		order: 52,
		revealOrder: 76,
	},
	{
		id: '053',
		slug: 'an-najm',
		name: 'An-Najm',
		nameAl: 'Ylli',
		shqiperuar: 'En-Nexhm',
		arabicName: 'النّجْم',
		place: 'Mekë',
		ayahs: 62,
		words: 738,
		chars: 3072,
		theme: 'Shpallja, misioni profetik, idhujtaria dhe madhështia e Allahut.',
		keyMessage: 'Mos e ndiq hamendjen kur udhëzimi hyjnor është i qartë.',
		order: 53,
		revealOrder: 23,
	},
	{
		id: '054',
		slug: 'al-qamar',
		name: 'Al-Qamar',
		nameAl: 'Hëna',
		arabicName: 'القمر',
		shqiperuar: 'El-Kamer',
		place: 'Mekë',
		ayahs: 55,
		words: 723,
		chars: 3155,
		theme: 'Shenja e hënës, historitë e popujve të Nuhut, Adit, Themudit dhe Lutit.',
		keyMessage: 'Mësimet e historisë janë paralajmërim për ata që refuzojnë të vërtetën.',
		order: 54,
		revealOrder: 37,
	},
	{
		id: '055',
		slug: 'ar-rahman',
		name: 'Ar-Rahmān',
		nameAl: 'Mëshiruesi',
		arabicName: 'الرّحْمن',
		shqiperuar: 'Er-Rrahman',
		place: 'Medinë',
		ayahs: 78,
		words: 815,
		chars: 3278,
		theme: 'Begatitë e panumërta të Allahut për njerëzit dhe xhinët.',
		keyMessage: 'Të njohim, vlerësojmë dhe falënderojmë Allahun për begatitë e Tij.',
		order: 55,
		revealOrder: 97,
	},
	{
		id: '056',
		slug: 'waqiah',
		name: 'Al-Wāqiah',
		nameAl: 'Ndodhia',
		shqiperuar: 'El-Uakia',
		arabicName: 'الواقعة',
		place: 'Mekë',
		ayahs: 96,
		words: 849,
		chars: 3538,
		theme: 'Ndarja e njerëzve në tri grupe dhe përshkrimi i Ahiretit.',
		keyMessage: 'Jeta e përtejme është realiteti përfundimtar dhe veprat përcaktojnë pozitën e njeriut.',
		order: 56,
		revealOrder: 46,
	},
	{
		id: '057',
		slug: 'hadid',
		name: 'Al-Hadīd',
		nameAl: 'Hekuri',
		shqiperuar: 'El-Hadid',
		arabicName: 'الحديد',
		place: 'Medinë',
		ayahs: 29,
		words: 1188,
		chars: 5139,
		theme: 'Besimi, shpenzimi në rrugën e Allahut, kjo botë dhe qëndrueshmëria.',
		keyMessage: 'Mos lejo që pasuria dhe jeta e kësaj bote të të largojnë nga Allahu.',
		order: 57,
		revealOrder: 94,
	},
	{
		id: '058',
		slug: 'mujadila',
		name: 'Al-Mujādala',
		nameAl: 'Gruaja që debaton',
		shqiperuar: 'El-Muxhadile',
		arabicName: 'المجادلة',
		place: 'Medinë',
		ayahs: 22,
		words: 920,
		chars: 4111,
		theme: 'Drejtësia familjare, bisedat e fshehta, respekti dhe hipokrizia.',
		keyMessage: 'Allahu dëgjon edhe ankesën më të fshehtë dhe kërkon drejtësi.',
		order: 58,
		revealOrder: 105,
	},
	{
		id: '059',
		slug: 'hashr',
		name: 'Al-Hashr',
		nameAl: 'Tubimi',
		arabicName: 'الحشْر',
		shqiperuar: 'El-Hashr',
		place: 'Medinë',
		ayahs: 24,
		words: 897,
		chars: 3971,
		theme: 'Dëbimi i Beni Nadirëve, marrëdhëniet shoqërore dhe cilësitë e Allahut.',
		keyMessage: 'Besimtari duhet të mësojë nga historia dhe të pastrojë zemrën nga egoizmi.',
		order: 59,
		revealOrder: 101,
	},
	{
		id: '060',
		slug: 'mumtahana',
		name: 'Al-Mumtahana',
		nameAl: 'Gruaja e Sprovuar',
		arabicName: 'الممتحنة',
		shqiperuar: 'El-Mumtehine',
		place: 'Medinë',
		ayahs: 13,
		words: 715,
		chars: 3129,
		theme: 'Besnikëria, marrëdhëniet me jo-besimtarët dhe drejtësia.',
		keyMessage: 'Besimi nuk e përjashton drejtësinë dhe mirësinë ndaj të tjerëve.',
		order: 60,
		revealOrder: 91,
	},
	{
		id: '061',
		slug: 'saff',
		name: 'As-Saff',
		nameAl: 'Rreshtat e besimtarëve',
		arabicName: 'الصّفّ',
		shqiperuar: 'Es-Saff',
		place: 'Medinë',
		ayahs: 14,
		words: 425,
		chars: 1828,
		theme: 'Uniteti, sakrifica dhe thirrja e Isait për ardhjen e të Dërguarit.',
		keyMessage: 'Mos thuaj atë që nuk e bën; sinqeriteti duhet të bashkojë fjalën me veprën.',
		order: 61,
		revealOrder: 109,
	},
	{
		id: '062',
		slug: 'jumua',
		name: 'Al-Jumua',
		nameAl: 'Xhuma',
		arabicName: 'الجمعة',
		shqiperuar: 'El-Xhuma',
		place: 'Medinë',
		ayahs: 11,
		words: 341,
		chars: 1406,
		theme: 'Namazi i xhumasë, dërgimi i Profetit dhe rreziku i dijes pa vepra.',
		keyMessage: 'Mos lejo tregtinë dhe angazhimet e kësaj bote të të largojnë nga përmendja e Allahut.',
		order: 62,
		revealOrder: 110,
	},
	{
		id: '063',
		slug: 'munafiqun',
		name: 'Al-Munāfiqūn',
		nameAl: 'Hipokritët',
		arabicName: 'المنافقون',
		shqiperuar: 'El-Munafikun',
		place: 'Medinë',
		ayahs: 11,
		words: 367,
		chars: 1558,
		theme: 'Shenjat e hipokrizisë dhe mashtrimi i jashtëm pa besim të brendshëm.',
		keyMessage: 'Sinqeriteti i zemrës është më i rëndësishëm se paraqitja e jashtme.',
		order: 63,
		revealOrder: 104,
	},
	{
		id: '064',
		slug: 'taghabun',
		name: 'At-Taghābun',
		shqiperuar: 'Et-Tegabun',
		nameAl: 'Zhgënjim i ndërsjelltë',
		arabicName: 'التّغابن',
		place: 'Medinë',
		ayahs: 18,
		words: 503,
		chars: 2182,
		theme: 'Besimi, familja, sprovat, pasuria dhe dita e gjykimit.',
		keyMessage: 'Disa humbje të kësaj bote mund të jenë fitore në Ahiret nëse ruhet besimi.',
		order: 64,
		revealOrder: 108,
	},
	{
		id: '065',
		slug: 'talaq',
		name: 'At-Talāq',
		nameAl: 'Divorci',
		shqiperuar: 'Et-Talak',
		arabicName: 'الطّلاق',
		place: 'Medinë',
		ayahs: 12,
		words: 562,
		chars: 2511,
		theme: 'Rregullat e divorcit, pritja, furnizimi dhe mbështetja tek Allahu.',
		keyMessage: 'Edhe ndarja duhet të bëhet me drejtësi, maturi dhe devotshmëri.',
		order: 65,
		revealOrder: 99,
	},
	{
		id: '066',
		slug: 'tahrim',
		name: 'At-Tahrīm',
		nameAl: 'Ndalimi',
		arabicName: 'التّحريم',
		shqiperuar: 'Et-Tahrim',
		place: 'Medinë',
		ayahs: 12,
		words: 478,
		chars: 2115,
		theme: 'Jeta familjare e Profetit, pendimi dhe shembujt e grave të besimtarëve dhe mohuesve.',
		keyMessage: 'Marrëdhëniet familjare kërkojnë sinqeritet, përgjegjësi dhe pendim.',
		order: 66,
		revealOrder: 107,
	},
	{
		id: '067',
		slug: 'mulk',
		name: 'Al-Mulk',
		shqiperuar: 'El-Mulk',
		nameAl: 'Sovraniteti',
		arabicName: 'الملك',
		place: 'Medinë',
		ayahs: 30,
		words: 659,
		chars: 2707,
		theme: 'Madhështia e Allahut, krijimi, vdekja dhe jeta si sprovë.',
		keyMessage: 'Jeta është sprovë për të parë kush vepron më mirë.',
		order: 67,
		revealOrder: 77,
	},
	{
		id: '068',
		slug: 'qalam',
		name: 'Al-Qalam',
		nameAl: 'Lapsi',
		shqiperuar: 'El-Kalem',
		arabicName: 'القلم',
		place: 'Mekë',
		ayahs: 52,
		words: 650,
		chars: 2760,
		theme: 'Morali i Profetit, kundërshtarët dhe historia e pronarëve të kopshtit.',
		keyMessage: 'Karakteri i mirë dhe durimi janë shenja të fuqisë shpirtërore.',
		order: 68,
		revealOrder: 2,
	},
	{
		id: '069',
		slug: 'haqqah',
		name: 'Al-Hāqqah',
		shqiperuar: 'El-Hakka',
		nameAl: 'E Pashmangshmja',
		arabicName: 'الحآقّة',
		place: 'Medinë',
		ayahs: 52,
		words: 575,
		chars: 2318,
		theme: 'Dita e Gjykimit dhe shkatërrimi i popujve që mohuan.',
		keyMessage: 'Ahireti është realitet i pashmangshëm.',
		order: 69,
		revealOrder: 78,
	},
	{
		id: '070',
		slug: 'maarij',
		name: 'Al-Maārij',
		shqiperuar: 'El-Mearixh',
		nameAl: 'Shkallët e Larta',
		arabicName: 'المعارج',
		place: 'Medinë',
		ayahs: 44,
		words: 448,
		chars: 1945,
		theme: 'Dita e Gjykimit dhe cilësitë e njerëzve të shpëtuar.',
		keyMessage: 'Durimi, namazi dhe përgjegjësia morale e pastrojnë njeriun.',
		order: 70,
		revealOrder: 79,
	},
	{
		id: '071',
		slug: 'nuh-a.s',
		name: 'Nūh',
		nameAl: 'Nuh a.s',
		arabicName: 'نوح',
		shqiperuar: 'Nuh a.s',
		place: 'Mekë',
		ayahs: 28,
		words: 227,
		chars: 965,
		theme: 'Thirrja e gjatë e Nuhut, këmbëngulja dhe përgjigjja e popullit të tij.',
		keyMessage: 'Thirrja në të mirë kërkon durim edhe kur rezultatet duken të pakta.',
		order: 71,
		revealOrder: 71,
	},
	{
		id: '072',
		slug: 'jinn',
		name: 'Al-Jinn',
		nameAl: 'Xhindët',
		shqiperuar: 'El_xhinn',
		arabicName: 'الجن',
		place: 'Mekë',
		ayahs: 28,
		words: 285,
		chars: 1103,
		theme: 'Xhinët që dëgjojnë Kuranin, teuhidi dhe kufijtë e dijes njerëzore.',
		keyMessage: 'Edhe krijesat e padukshme janë nën pushtetin e Allahut dhe duhet të adhurojnë vetëm Atë.',
		order: 72,
		revealOrder: 40,
	},
	{
		id: '073',
		slug: 'al-muzzammil',
		name: 'Al-Muzzammil',
		nameAl: 'I Mbështjelluri',
		shqiperuar: 'El-Muzzemmil',
		arabicName: 'المزمل',
		place: 'Mekë',
		ayahs: 20,
		words: 244,
		chars: 1003,
		theme: 'Namazi i natës, leximi i Kuranit, durimi dhe përgatitja shpirtërore.',
		keyMessage: 'Forca për misionin dhe jetën vjen nga lidhja e thellë me Allahun.',
		order: 73,
		revealOrder: 3,
	},
	{
		id: '074',
		slug: 'al-muddathir',
		name: 'Al-Muddathir',
		shqiperuar: 'El-Muddeththir',
		nameAl: 'I Mbuluari',
		arabicName: 'المدثر',
		place: 'Mekë',
		ayahs: 56,
		words: 257,
		chars: 1036,
		theme: "Thirrja për t'u ngritur e paralajmëruar, pastërtia dhe përgjegjësia.",
		keyMessage: 'Besimtari duhet të ngrihet për të bërë të mirën dhe për të paralajmëruar me urtësi.',
		order: 74,
		revealOrder: 4,
	},
	{
		id: '075',
		slug: 'al-qiyamah',
		name: 'Al-Qiyāmah',
		nameAl: 'Ringjallja',
		shqiperuar: 'El-Kijame',
		arabicName: 'القيامة',
		place: 'Mekë',
		ayahs: 40,
		words: 164,
		chars: 676,
		theme: 'Ringjallja, ndërgjegjja dhe dita kur njeriu përballet me veprat e tij.',
		keyMessage: "Askush nuk mund t'i shmanget përgjegjësisë përpara Allahut.",
		order: 75,
		revealOrder: 31,
	},
	{
		id: '076',
		slug: 'al-insan',
		name: 'Al-Insān',
		nameAl: 'Njeriu',
		shqiperuar: 'El-Insan',
		arabicName: 'الإنسان',
		place: 'Medinë',
		ayahs: 31,
		words: 241,
		chars: 1102,
		theme: 'Krijimi i njeriut, mirësia, durimi dhe shpërblimi i të devotshmëve.',
		keyMessage: 'Veprat e mira të bëra me sinqeritet kanë shpërblim të madh.',
		order: 76,
		revealOrder: 98,
	},
	{
		id: '077',
		slug: 'al-mursalat',
		name: 'Al-Mursalāt',
		shqiperuar: 'El-Murselat',
		nameAl: 'Engjëjt e Dërguar',
		arabicName: 'المرسلات',
		place: 'Mekë',
		ayahs: 50,
		words: 181,
		chars: 774,
		theme: 'Dita e Gjykimit, shenjat e krijimit dhe paralajmërimi i mohuesve.',
		keyMessage: 'E vërteta e gjykimit hyjnor është e sigurt.',
		order: 77,
		revealOrder: 33,
	},
	{
		id: '078',
		slug: 'naba',
		name: 'An-Naba',
		shqiperuar: 'En-Nebe',
		nameAl: 'Lajmi i Madh',
		arabicName: 'النبأ',
		place: 'Mekë',
		ayahs: 40,
		words: 174,
		chars: 762,
		theme: 'Lajmi i madh i ringjalljes, krijimi dhe Dita e Gjykimit.',
		keyMessage: 'Jeta nuk përfundon me vdekjen; ringjallja është pjesë e drejtësisë hyjnore.',
		order: 78,
		revealOrder: 80,
	},
	{
		id: '079',
		slug: 'an-naziat',
		name: 'An-Nāzi`āt',
		shqiperuar: 'En-Naziat',
		nameAl: 'Ata që tërheqin',
		arabicName: 'النازعات',
		place: 'Mekë',
		ayahs: 46,
		words: 179,
		chars: 769,
		theme: 'Engjëjt, ringjallja dhe historia e Musait me Faraonin.',
		keyMessage: 'Fuqia e Allahut mbi krijimin dhe ringjalljen është absolute.',
		order: 79,
		revealOrder: 81,
	},
	{
		id: '080',
		slug: 'abasa',
		name: 'Abasa',
		shqiperuar: 'Abese',
		nameAl: 'Ai U Vrenjt',
		arabicName: 'عبس',
		place: 'Mekë',
		ayahs: 42,
		words: 133,
		chars: 553,
		theme: 'Ngjarja me njeriun e verbër, rëndësia e sinqeritetit dhe shpalljes.',
		keyMessage: 'Mos e mat vlerën e njeriut me statusin e tij shoqëror.',
		order: 80,
		revealOrder: 24,
	},
	{
		id: '081',
		slug: 'at-takwir',
		name: 'At-Takwīr',
		shqiperuar: 'Et-Tekuir',
		nameAl: 'Rrotullimi (Errësimi)',
		arabicName: 'التكوير',
		place: 'Mekë',
		ayahs: 29,
		words: 104,
		chars: 432,
		theme: 'Shenjat e Kijametit dhe vërtetësia e shpalljes.',
		keyMessage: 'Kjo botë do të ndryshojë dhe njeriu duhet të përgatitet për Ahiretin.',
		order: 81,
		revealOrder: 7,
	},
	{
		id: '082',
		slug: 'al-infitar',
		name: 'Al-Infitār',
		shqiperuar: 'El-Infitar',
		nameAl: 'Çarja e qiellit',
		arabicName: 'الإنفطار',
		place: 'Mekë',
		ayahs: 19,
		words: 81,
		chars: 329,
		theme: 'Çarja e qiellit, regjistrimi i veprave dhe Dita e Gjykimit.',
		keyMessage: 'Njeriu duhet të kujtojë se çdo vepër e tij është e regjistruar.',
		order: 82,
		revealOrder: 82,
	},
	{
		id: '083',
		slug: 'al-mutaffifin',
		name: 'Al-Mutaffifīn',
		shqiperuar: 'El-Mutaffifin',
		nameAl: 'Mashtruesit në peshore',
		arabicName: 'المطففين',
		place: 'Mekë',
		ayahs: 36,
		words: 169,
		chars: 738,
		theme: 'Mashtrimi në peshë dhe masë, drejtësia dhe regjistrimi i veprave.',
		keyMessage: 'Ndershmëria në tregti dhe në çdo marrëdhënie është detyrim moral.',
		order: 83,
		revealOrder: 86,
	},
	{
		id: '084',
		slug: 'al-inshiqaq',
		name: 'Al-Inshiqāq',
		shqiperuar: 'El-Inshikak',
		nameAl: 'Bindja',
		arabicName: 'الإنشقاق',
		place: 'Mekë',
		ayahs: 25,
		words: 105,
		chars: 425,
		theme: 'Dita e Gjykimit dhe libri i veprave që i jepet njeriut.',
		keyMessage: 'Çdo njeri do të takohet me rezultatet e përpjekjeve të tij.',
		order: 84,
		revealOrder: 83,
	},
	{
		id: '085',
		slug: 'al-buruj',
		name: 'Al-Burūj',
		nameAl: 'Yjësitë',
		shqiperuar: 'El-Buruxh',
		arabicName: 'البروج',
		place: 'Mekë',
		ayahs: 22,
		words: 92,
		chars: 372,
		theme: 'Besimtarët e përndjekur dhe tirania e mohuesve.',
		keyMessage: 'Besimi i sinqertë mund të kërkojë sakrificë, por Allahu nuk e harron padrejtësinë.',
		order: 85,
		revealOrder: 27,
	},
	{
		id: '086',
		slug: 'at-tariq',
		name: 'At-Tāriq',
		shqiperuar: 'Et-Tarik',
		nameAl: 'Ylli i Mëngjesit',
		arabicName: 'الطارق',
		place: 'Mekë',
		ayahs: 17,
		words: 61,
		chars: 250,
		theme: 'Krijimi i njeriut dhe fuqia e Allahut për ta ringjallur.',
		keyMessage: 'Ai që e krijoi njeriun mund ta rikthejë në jetë.',
		order: 86,
		revealOrder: 36,
	},
	{
		id: '087',
		slug: 'al-ala',
		name: 'Al-Aʻlā',
		shqiperuar: 'El-Ala',
		nameAl: 'Më i Larti',
		arabicName: 'الأعلى',
		place: 'Mekë',
		ayahs: 19,
		words: 72,
		chars: 296,
		theme: 'Lavdërimi i Allahut, krijimi, shpallja dhe pastrimi shpirtëror.',
		keyMessage: 'Përmendja e Allahut dhe pastrimi i shpirtit janë rrugë drejt suksesit.',
		order: 87,
		revealOrder: 8,
	},
	{
		id: '088',
		slug: 'al-ghashiyah',
		name: 'Al-Ghāshiyah',
		shqiperuar: 'El-Gashije',
		nameAl: 'Ngjarja Pushtuese',
		arabicName: 'الغاشية',
		place: 'Mekë',
		ayahs: 26,
		words: 92,
		chars: 368,
		theme: 'Xheneti dhe Xhehenemi dhe shenjat e Allahut në krijim.',
		keyMessage: 'Reflektimi mbi krijimin dhe Ahiretin e forcon ndërgjegjen.',
		order: 88,
		revealOrder: 68,
	},
	{
		id: '089',
		slug: 'al-fajr',
		name: 'Al-Fajr',
		nameAl: 'Agimi',
		shqiperuar: 'El-Fexhr',
		arabicName: 'الفجر',
		place: 'Mekë',
		ayahs: 30,
		words: 139,
		chars: 584,
		theme: 'Popujt e fuqishëm të shkatërruar, sprova e pasurisë dhe varfërisë dhe shpirti i qetë.',
		keyMessage: 'Pasuria dhe varfëria janë sprova; nderi i vërtetë lidhet me drejtësinë dhe besimin.',
		order: 89,
		revealOrder: 10,
	},
	{
		id: '090',
		slug: 'al-balad',
		name: 'Al-Balad',
		shqiperuar: 'El-Beled',
		nameAl: 'Qyteti',
		arabicName: 'البلد',
		place: 'Mekë',
		ayahs: 20,
		words: 82,
		chars: 337,
		theme: 'Vështirësia e jetës dhe rruga e veprave të mira.',
		keyMessage: 'Rruga e drejtë kërkon përpjekje, mëshirë dhe çlirimin e të tjerëve nga vështirësitë.',
		order: 90,
		revealOrder: 35,
	},
	{
		id: '091',
		slug: 'ash-shams',
		name: 'Ash-Shams',
		shqiperuar: 'Esh-Shems',
		nameAl: 'Dielli',
		arabicName: 'الشمس',
		place: 'Mekë',
		ayahs: 15,
		words: 54,
		chars: 245,
		theme: 'Pastrimi i shpirtit dhe historia e Themudit.',
		keyMessage: 'Ka shpëtuar ai që e pastron shpirtin dhe ka dështuar ai që e korrupton.',
		order: 91,
		revealOrder: 26,
	},
	{
		id: '092',
		slug: 'al-lail',
		name: 'Al-Lail',
		shqiperuar: 'El-Lejl',
		nameAl: 'Nata',
		arabicName: 'الليل',
		place: 'Mekë',
		ayahs: 21,
		words: 71,
		chars: 295,
		theme: 'Dy rrugët e njeriut: dhënia dhe devotshmëria përballë koprracisë dhe mohimit.',
		keyMessage: 'Veprat, qëllimet dhe bujaria formojnë rrugën e njeriut.',
		order: 92,
		revealOrder: 9,
	},
	{
		id: '093',
		slug: 'ad-duha',
		name: 'Ad-Duḥā',
		shqiperuar: 'Ed-Duha',
		nameAl: 'Mëngjesi',
		arabicName: 'الضحى',
		place: 'Mekë',
		ayahs: 11,
		words: 40,
		chars: 165,
		theme: 'Ngushëllimi i Profetit dhe kujtesa për mëshirën e Allahut.',
		keyMessage: 'Kur njeriu ndihet i vetëm, duhet të kujtojë mirësitë dhe kujdesin e Allahut.',
		order: 93,
		revealOrder: 11,
	},
	{
		id: '094',
		slug: 'ash-sharh',
		name: 'Ash-Sharḥ',
		shqiperuar: 'El-Inshirah',
		nameAl: 'Zgjerimi i Kraharorit',
		arabicName: 'الشرح',
		place: 'Mekë',
		ayahs: 8,
		words: 30,
		chars: 120,
		theme: 'Lehtësimi pas vështirësisë dhe mbështetja tek Allahu.',
		keyMessage: 'Me vështirësinë vjen lehtësimi; mos e humb shpresën.',
		order: 94,
		revealOrder: 12,
	},
	{
		id: '095',
		slug: 'at-tin',
		name: 'At-Tīn',
		nameAl: 'Fiku',
		shqiperuar: 'Et-Tin',
		arabicName: 'التين',
		place: 'Mekë',
		ayahs: 8,
		words: 34,
		chars: 144,
		theme: 'Krijimi i njeriut në formën më të bukur dhe përgjegjësia morale.',
		keyMessage: 'Njeriu ka potencial të lartë, por duhet ta ruajë atë përmes besimit dhe veprave të mira.',
		order: 95,
		revealOrder: 28,
	},
	{
		id: '096',
		slug: 'al-alaq',
		name: 'Al-Alaq',
		nameAl: 'Mpiksja',
		shqiperuar: 'El-Alak',
		arabicName: 'العلق',
		place: 'Mekë',
		ayahs: 19,
		words: 92,
		chars: 380,
		theme: 'Shpallja e parë, leximi, krijimi dhe arroganca e njeriut.',
		keyMessage: 'Dija duhet të fillojë me emrin e Allahut dhe të shoqërohet me përulësi.',
		order: 96,
		revealOrder: 1,
	},
	{
		id: '097',
		slug: 'al-qadr',
		name: 'Al-Qadr',
		shqiperuar: 'El-Kadr',
		nameAl: 'Natë e Caktimit/Fuqishme',
		arabicName: 'القدر',
		place: 'Mekë',
		ayahs: 5,
		words: 30,
		chars: 114,
		theme: 'Madhështia e Natës së Kadrit dhe zbritja e Kuranit.',
		keyMessage: 'Nata e Kadrit ka vlerë të jashtëzakonshme dhe është kohë adhurimi e afrimi me Allahun.',
		order: 97,
		revealOrder: 25,
	},
	{
		id: '098',
		slug: 'al-bayyinah',
		name: 'Al-Bayyinah',
		shqiperuar: 'El-Bejjine',
		nameAl: 'Prova e Qartë',
		arabicName: 'البينة',
		place: 'Medinë',
		ayahs: 8,
		words: 102,
		chars: 427,
		theme: 'Dëshmia e qartë, sinqeriteti në adhurim dhe ndarja e njerëzve sipas besimit e veprave.',
		keyMessage: 'Thelbi i fesë është adhurimi i Allahut me sinqeritet dhe drejtësi.',
		order: 98,
		revealOrder: 100,
	},
	{
		id: '099',
		slug: 'az-zalzalah',
		name: 'Az-Zalzalah',
		shqiperuar: 'Ez-Zelzele',
		nameAl: 'Tërmeti',
		arabicName: 'الزلزلة',
		place: 'Medinë',
		ayahs: 8,
		words: 36,
		chars: 158,
		theme: 'Tërmeti i Kijametit dhe shfaqja e çdo vepre, sado e vogël.',
		keyMessage: 'Asnjë e mirë apo e keqe nuk humbet.',
		order: 99,
		revealOrder: 93,
	},
	{
		id: '100',
		slug: 'al-adiyat',
		name: 'Al-ʻĀdiyāt',
		shqiperuar: 'El-Adijat',
		nameAl: 'Kuajt',
		arabicName: 'العاديات',
		place: 'Mekë',
		ayahs: 11,
		words: 40,
		chars: 176,
		theme: 'Natyra e njeriut që bëhet mosmirënjohës dhe i lidhur me pasurinë.',
		keyMessage: 'Njeriu duhet të ruhet nga lakmia dhe mosmirënjohja.',
		order: 100,
		revealOrder: 14,
	},
	{
		id: '101',
		slug: 'qariah',
		name: 'Al-Qāriʻah',
		shqiperuar: 'El-Karia',
		nameAl: 'Krismat',
		arabicName: 'القارعة',
		place: 'Mekë',
		ayahs: 11,
		words: 36,
		chars: 158,
		theme: 'Dita e Kijametit dhe peshorja e veprave.',
		keyMessage: 'Vlera e njeriut në Ahiret lidhet me peshën e veprave të tij.',
		order: 101,
		revealOrder: 30,
	},
	{
		id: '102',
		slug: 'at-takathur',
		name: 'At-Takāthur',
		shqiperuar: 'El-Tekathur',
		nameAl: 'Garimi për më shumë-Krenaria',
		arabicName: 'التكاثر',
		place: 'Mekë',
		ayahs: 8,
		words: 28,
		chars: 120,
		theme: 'Gara për pasuri dhe numërim dhe harresa e Ahiretit.',
		keyMessage: 'Mos lejo garën për gjëra materiale të të largojë nga qëllimi i jetës.',
		order: 102,
		revealOrder: 16,
	},
	{
		id: '103',
		slug: 'al-asr',
		name: 'Al-ʻAsr',
		nameAl: 'Koha',
		shqiperuar: 'El-Asr',
		arabicName: 'العصر',
		place: 'Mekë',
		ayahs: 3,
		words: 14,
		chars: 68,
		theme: 'Koha, humbja e njeriut, besimi, veprat e mira, këshillimi për të vërtetën dhe durimin.',
		keyMessage: 'Njeriu shpëton përmes besimit, veprave të mira, së vërtetës dhe durimit.',
		order: 103,
		revealOrder: 13,
	},
	{
		id: '104',
		slug: 'al-humazah',
		name: 'Al-Humazah',
		nameAl: 'Përqeshësi',
		shqiperuar: 'El-Humuze',
		arabicName: 'الهمزة',
		place: 'Mekë',
		ayahs: 9,
		words: 33,
		chars: 133,
		theme: 'Përgojimi, tallja dhe grumbullimi i pasurisë.',
		keyMessage: 'Pasuria nuk e shpëton njeriun nga përgjegjësia dhe gjykimi.',
		order: 104,
		revealOrder: 32,
	},
	{
		id: '105',
		slug: 'al-fil',
		name: 'Al-Fīl',
		nameAl: 'Elefanti',
		shqiperuar: 'El-Fil',
		arabicName: 'الفيل',
		place: 'Mekë',
		ayahs: 5,
		words: 23,
		chars: 96,
		theme: 'Ushtria e elefantit dhe mbrojtja e Qabes nga Allahu.',
		keyMessage: 'Fuqia e Allahut është mbi çdo fuqi njerëzore.',
		order: 105,
		revealOrder: 19,
	},
	{
		id: '106',
		slug: 'quraish',
		name: 'Quraish',
		nameAl: 'Kureishitët',
		shqiperuar: 'El-Kurejsh',
		arabicName: 'قريش',
		place: 'Mekë',
		ayahs: 4,
		words: 17,
		chars: 73,
		theme: 'Begatitë e sigurisë dhe furnizimit që iu dhanë Kurejshëve.',
		keyMessage: 'Begatitë duhet të çojnë në adhurim dhe mirënjohje.',
		order: 106,
		revealOrder: 29,
	},
	{
		id: '107',
		slug: 'maun',
		name: 'Al-Māʻūn',
		nameAl: 'Ndihmesa e Vogël',
		shqiperuar: 'El-Maun',
		arabicName: 'الماعون',
		place: 'Mekë',
		ayahs: 7,
		words: 25,
		chars: 114,
		theme: 'Mohimi praktik i fesë, neglizhimi i jetimit, të varfrit dhe namazi pa sinqeritet.',
		keyMessage: 'Feja kërkon mëshirë dhe vepra të mira, jo vetëm paraqitje të jashtme.',
		order: 107,
		revealOrder: 17,
	},
	{
		id: '108',
		slug: 'al-kauthar',
		name: 'Al-Kawthar',
		shqiperuar: 'El-Keuther',
		nameAl: 'Begatia e Madhe',
		arabicName: 'الكوثر',
		place: 'Mekë',
		ayahs: 3,
		words: 10,
		chars: 42,
		theme: 'Begatia e madhe që Allahu i dha Profetit dhe urdhri për namaz e kurban.',
		keyMessage: 'Përballë begative, përgjigjja është falënderimi dhe adhurimi.',
		order: 108,
		revealOrder: 15,
	},
	{
		id: '109',
		slug: 'al-kafiroon',
		name: 'Al-Kāfirūn',
		shqiperuar: 'El-Kafirun',
		nameAl: 'Jobesimtarët',
		arabicName: 'الكافرون',
		place: 'Mekë',
		ayahs: 6,
		words: 27,
		chars: 94,
		theme: 'Qëndrimi i qartë ndaj idhujtarisë dhe dallimi i adhurimit.',
		keyMessage: 'Besimi kërkon qartësi dhe sinqeritet në adhurim.',
		order: 109,
		revealOrder: 18,
	},
	{
		id: '110',
		slug: 'nasr',
		name: 'An-Naṣr',
		shqiperuar: 'En-Nasr',
		nameAl: 'Ndihma e Allahut',
		arabicName: 'النصر',
		place: 'Medinë',
		ayahs: 3,
		words: 19,
		chars: 80,
		theme: 'Fitorja e Allahut, hyrja e njerëzve në Islam dhe kërkimi i faljes.',
		keyMessage: 'Edhe pas suksesit, besimtari duhet të lavdërojë Allahun dhe të kërkojë falje.',
		order: 110,
		revealOrder: 114,
	},
	{
		id: '111',
		slug: 'masad',
		name: 'Al-Masad',
		nameAl: 'Litarët',
		shqiperuar: 'El-Mesed',
		arabicName: 'المسد',
		place: 'Mekë',
		ayahs: 5,
		words: 23,
		chars: 94,
		theme: 'Abu Lehebi dhe gruaja e tij si shembuj të armiqësisë ndaj së vërtetës.',
		keyMessage: 'Pasuria dhe statusi nuk e shpëtojnë njeriun kur ai refuzon të vërtetën.',
		order: 111,
		revealOrder: 6,
	},
	{
		id: '112',
		slug: 'al-ikhlas',
		name: 'Al-Ikhlāṣ',
		shqiperuar: 'El-Ihlas',
		nameAl: 'Sinqeriteti i besimit',
		arabicName: 'الإخلاص',
		place: 'Mekë',
		ayahs: 4,
		words: 15,
		chars: 47,
		theme: 'Përshkrimi i teuhidit dhe unikësisë absolute të Allahut.',
		keyMessage: 'Allahu është Një, i Pavarur dhe i pakrahasueshëm.',
		order: 112,
		revealOrder: 22,
	},
	{
		id: '113',
		slug: 'al-falaq',
		name: 'Al-Falaq',
		shqiperuar: 'El-Felek',
		nameAl: 'Agimi i sabahut',
		arabicName: 'الفلق',
		place: 'Mekë',
		ayahs: 5,
		words: 23,
		chars: 79,
		theme: 'Kërkimi i mbrojtjes së Allahut nga të këqijat e krijesave, errësira, magjia dhe zilia.',
		keyMessage: 'Besimtari kërkon mbrojtje te Allahu nga çdo e keqe e dukshme dhe e fshehtë.',
		order: 113,
		revealOrder: 20,
	},
	{
		id: '114',
		slug: 'an-nas',
		name: 'An-Nās',
		shqiperuar: 'En-Nas',
		nameAl: 'Njerëzit',
		arabicName: 'الناس',
		place: 'Mekë',
		ayahs: 6,
		words: 20,
		chars: 80,
		theme: 'Kërkimi i mbrojtjes te Zoti, Mbreti dhe i Adhuruari i njerëzve nga vesveset e shejtanit.',
		keyMessage: 'Mbrojtja më e sigurt ndaj vesveseve është kthimi i vazhdueshëm tek Allahu.',
		order: 114,
		revealOrder: 21,
	},
];
